[package]
name = "htu-toolbox-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1"
curl = { version = "0.4" }
url = "2"
serde = { version = "1", features = ["derive"]}
serde_json = "1"
thiserror = "2"

[dev-dependencies]
tokio = { version = "1", features = ["macros"]}
